root: true
env:
  browser: true
  es2020: true
  node: true
parser: '@typescript-eslint/parser'
parserOptions:
  sourceType: module
  ecmaVersion: latest
plugins: [svelte3, '@typescript-eslint']
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
overrides:
  - files: ['*.svelte']
    processor: svelte3/svelte3
settings:
  svelte3/typescript: true
rules:
  indent: [error, 2, SwitchCase: 1]
  '@typescript-eslint/quotes': [error, backtick, avoidEscape: true]
  semi: [error, never]
  linebreak-style: [error, unix]
  no-console: [error, allow: [warn, error]]
  no-var: error
  # allow triple slash for typescript file referencing https://git.io/JCeqO
  spaced-comment: [error, always, { markers: [/] }]
globals:
  $$props: false # declare the Svelte $$props object as a non-writable global variable
  google: false
