name: GitHub Pages

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    uses: janosh/workflows/.github/workflows/deno-gh-pages.yml@main
    secrets: inherit
    with:
      deno-version: 2.3.7 # https://github.com/denoland/deno/issues/29968, https://github.com/pngwn/MDsveX/issues/743
